add_newline = true

command_timeout = 3000
[character] # The name of the module we are configuring is 'character'
# format = '[󰅂](bold green)' # The 'format' segment is being set to '➜' with the color 'bold green'
success_symbol = '[󰅂](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[󰅂](bold red)'

# [Prompt]
# command_timeout = 1000
#
