[manager]
show_hidden = true

[preview]
max_width = 920
max_height = 920

[opener]
play_folder = [
  { run = 'mpv --video-unscaled=downscale-big .', orphan = true, desc = "Play all in folder" },
]
play_unscaled = [
  { run = 'mpv --video-unscaled=downscale-big "$@"', orphan = true, desc = "MPV (Unscaled)" },
]
play_standard = [{ run = 'mpv "$@"', orphan = true, desc = "MPV (Standard)" }]
play_vlc = [{ run = 'vlc "$@"', orphan = true, desc = "VLC Player" }]
edit = [{ run = 'nvim "$@"', block = true, desc = "Edit" }]
play_image = [
  { run = 'mpv --image-display-duration=inf "$@"', orphan = true, desc = "MPV (Image)" },
]

[[open.prepend_rules]]
mime = "video/*"
# Added "reveal" and "open" to maintain default metadata/preview links
use = [
  "play_unscaled",
  "play_standard",
  "play_vlc",
  "play_folder",
  "reveal",
  "open",
]
# [[open.prepend_rules]]
# mime = "image/*"
# This ensures images always fall back to the internal viewer (where EXIF lives)
#use = ["open", "reveal"]
[[open.prepend_rules]]
mime = "image/*"
use = ["play_image", "open", "reveal"]
[[open.prepend_rules]]
mime = "inode/directory"
use = ["play_folder", "open", "reveal"]
