n playlist-next      # Bind 'n' to next file
p playlist-prev      # Bind 'p' to previous file
Shift+DEL run "rm" "${path}" ; playlist-next
y run "sh" "-c" "/usr/bin/wl-copy --type image/png < '${path}'" ; playlist-next
